import type { LucideProps } from "lucide-react";
import {
  Activity,
  AppWindow,
  ArrowUpRight,
  BadgeCheck,
  BarChart3,
  BookOpen,
  Boxes,
  Briefcase,
  Building2,
  Cable,
  Calculator,
  CalendarClock,
  Circle,
  Cloud,
  Code2,
  Compass,
  Database,
  Factory,
  FileText,
  FlaskConical,
  Gauge,
  GitBranch,
  GitCompare,
  GraduationCap,
  HardDrive,
  Headphones,
  Headset,
  HelpCircle,
  History,
  Info,
  KeyRound,
  Laptop,
  Layers,
  LayoutGrid,
  Lightbulb,
  LineChart,
  Lock,
  MonitorPlay,
  MousePointerClick,
  Network,
  PackageSearch,
  Presentation,
  Repeat,
  Rocket,
  Route,
  Server,
  Settings2,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Terminal,
  Truck,
  UserCheck,
  Users,
  Wallet,
  Warehouse,
  Wifi,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";

/**
 * Explicit registry of the icons referenced by name in src/data/*.
 * Importing the icons individually (instead of `import * as Lucide`) keeps the
 * whole Lucide library out of the client bundle.
 */
const registry: Record<string, React.ComponentType<LucideProps>> = {
  Activity,
  AppWindow,
  ArrowUpRight,
  BadgeCheck,
  BarChart3,
  BookOpen,
  Boxes,
  Briefcase,
  Building2,
  Cable,
  Calculator,
  CalendarClock,
  Cloud,
  Code2,
  Compass,
  Database,
  Factory,
  FileText,
  FlaskConical,
  Gauge,
  GitBranch,
  GitCompare,
  GraduationCap,
  HardDrive,
  Headphones,
  Headset,
  HelpCircle,
  History,
  Info,
  KeyRound,
  Laptop,
  Layers,
  LayoutGrid,
  Lightbulb,
  LineChart,
  Lock,
  MonitorPlay,
  MousePointerClick,
  Network,
  PackageSearch,
  Presentation,
  Repeat,
  Rocket,
  Route,
  Server,
  Settings2,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Terminal,
  Truck,
  UserCheck,
  Users,
  Wallet,
  Warehouse,
  Wifi,
  Workflow,
  Wrench,
  Zap,
};

/** Renders a Lucide icon by name (icon names are stored in src/data/serverfy.ts). */
export function Icon({ name, ...props }: { name: string } & LucideProps) {
  const Cmp = registry[name] ?? Circle;
  return <Cmp aria-hidden="true" {...props} />;
}
