/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as LlmDottxtRouteImport } from './routes/llm[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SlaRouteImport } from './routes/sla'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WhyServerfyRouteImport } from './routes/why-serverfy'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ModulesIndexRouteImport } from './routes/modules.index'
import { Route as ModulesCodeRouteImport } from './routes/modules.$code'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as ServersIndexRouteImport } from './routes/servers.index'
import { Route as ServersSlugRouteImport } from './routes/servers.$slug'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmDottxtRoute = LlmDottxtRouteImport.update({
  id: '/llm.txt',
  path: '/llm.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SlaRoute = SlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyServerfyRoute = WhyServerfyRouteImport.update({
  id: '/why-serverfy',
  path: '/why-serverfy',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ModulesIndexRoute = ModulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesCodeRoute = ModulesCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => ModulesRoute,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const ServersIndexRoute = ServersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServersRoute,
} as any)
const ServersSlugRoute = ServersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServersRoute,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SolutionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/infrastructure': typeof InfrastructureRoute
  '/llm.txt': typeof LlmDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/modules': typeof ModulesRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/servers': typeof ServersRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sla': typeof SlaRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/why-serverfy': typeof WhyServerfyRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/modules/$code': typeof ModulesCodeRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/servers/$slug': typeof ServersSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/servers/': typeof ServersIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/infrastructure': typeof InfrastructureRoute
  '/llm.txt': typeof LlmDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sla': typeof SlaRoute
  '/terms': typeof TermsRoute
  '/why-serverfy': typeof WhyServerfyRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/modules/$code': typeof ModulesCodeRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/servers/$slug': typeof ServersSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/modules': typeof ModulesIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/servers': typeof ServersIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/infrastructure': typeof InfrastructureRoute
  '/llm.txt': typeof LlmDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/modules': typeof ModulesRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/servers': typeof ServersRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sla': typeof SlaRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/why-serverfy': typeof WhyServerfyRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/modules/$code': typeof ModulesCodeRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/servers/$slug': typeof ServersSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/servers/': typeof ServersIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/infrastructure'
    | '/llm.txt'
    | '/llms.txt'
    | '/mcp'
    | '/modules'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/resources'
    | '/servers'
    | '/sitemap.xml'
    | '/sla'
    | '/solutions'
    | '/terms'
    | '/why-serverfy'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/modules/$code'
    | '/resources/$slug'
    | '/servers/$slug'
    | '/solutions/$slug'
    | '/blog/'
    | '/modules/'
    | '/resources/'
    | '/servers/'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/infrastructure'
    | '/llm.txt'
    | '/llms.txt'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/sla'
    | '/terms'
    | '/why-serverfy'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/modules/$code'
    | '/resources/$slug'
    | '/servers/$slug'
    | '/solutions/$slug'
    | '/blog'
    | '/modules'
    | '/resources'
    | '/servers'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/infrastructure'
    | '/llm.txt'
    | '/llms.txt'
    | '/mcp'
    | '/modules'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/resources'
    | '/servers'
    | '/sitemap.xml'
    | '/sla'
    | '/solutions'
    | '/terms'
    | '/why-serverfy'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/modules/$code'
    | '/resources/$slug'
    | '/servers/$slug'
    | '/solutions/$slug'
    | '/blog/'
    | '/modules/'
    | '/resources/'
    | '/servers/'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  InfrastructureRoute: typeof InfrastructureRoute
  LlmDottxtRoute: typeof LlmDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  McpRoute: typeof McpRoute
  ModulesRoute: typeof ModulesRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  ServersRoute: typeof ServersRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SlaRoute: typeof SlaRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  TermsRoute: typeof TermsRoute
  WhyServerfyRoute: typeof WhyServerfyRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm.txt': {
      id: '/llm.txt'
      path: '/llm.txt'
      fullPath: '/llm.txt'
      preLoaderRoute: typeof LlmDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sla': {
      id: '/sla'
      path: '/sla'
      fullPath: '/sla'
      preLoaderRoute: typeof SlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-serverfy': {
      id: '/why-serverfy'
      path: '/why-serverfy'
      fullPath: '/why-serverfy'
      preLoaderRoute: typeof WhyServerfyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/modules/': {
      id: '/modules/'
      path: '/'
      fullPath: '/modules/'
      preLoaderRoute: typeof ModulesIndexRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/$code': {
      id: '/modules/$code'
      path: '/$code'
      fullPath: '/modules/$code'
      preLoaderRoute: typeof ModulesCodeRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/servers/': {
      id: '/servers/'
      path: '/'
      fullPath: '/servers/'
      preLoaderRoute: typeof ServersIndexRouteImport
      parentRoute: typeof ServersRoute
    }
    '/servers/$slug': {
      id: '/servers/$slug'
      path: '/$slug'
      fullPath: '/servers/$slug'
      preLoaderRoute: typeof ServersSlugRouteImport
      parentRoute: typeof ServersRoute
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof SolutionsRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ModulesRouteChildren {
  ModulesCodeRoute: typeof ModulesCodeRoute
  ModulesIndexRoute: typeof ModulesIndexRoute
}

const ModulesRouteChildren: ModulesRouteChildren = {
  ModulesCodeRoute: ModulesCodeRoute,
  ModulesIndexRoute: ModulesIndexRoute,
}

const ModulesRouteWithChildren =
  ModulesRoute._addFileChildren(ModulesRouteChildren)

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface ServersRouteChildren {
  ServersSlugRoute: typeof ServersSlugRoute
  ServersIndexRoute: typeof ServersIndexRoute
}

const ServersRouteChildren: ServersRouteChildren = {
  ServersSlugRoute: ServersSlugRoute,
  ServersIndexRoute: ServersIndexRoute,
}

const ServersRouteWithChildren =
  ServersRoute._addFileChildren(ServersRouteChildren)

interface SolutionsRouteChildren {
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsSlugRoute: SolutionsSlugRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  InfrastructureRoute: InfrastructureRoute,
  LlmDottxtRoute: LlmDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  McpRoute: McpRoute,
  ModulesRoute: ModulesRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  ServersRoute: ServersRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SlaRoute: SlaRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  TermsRoute: TermsRoute,
  WhyServerfyRoute: WhyServerfyRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
